"""
Sightengine Detection Provider.
Integrates with Sightengine API for AI-generated IMAGE detection and deepfake face-swap detection.
Docs: https://sightengine.com/docs/ai-generated-image-detection
      https://sightengine.com/docs/deepfake-detection
NOTE: Video detection is handled by Reality Defender. This provider is IMAGE-ONLY.
"""

import os
import uuid
import httpx
from typing import Any, Dict, Optional
from app.detection.base import DetectionProvider

SIGHTENGINE_IMAGE_URL = "https://api.sightengine.com/1.0/check.json"


class SightengineDetectionProvider(DetectionProvider):
    """Sightengine AI deepfake & AI-generated IMAGE detection provider (image-only)."""

    def __init__(self, api_user: str = "", api_secret: str = ""):
        self._api_user = api_user or os.getenv("SIGHTENGINE_API_USER", "")
        self._api_secret = api_secret or os.getenv("SIGHTENGINE_API_SECRET", "")

    @property
    def provider_name(self) -> str:
        return "sightengine"

    def supports_modality(self, media_type: str) -> bool:
        """Sightengine supports image detection only."""
        return media_type == "image"

    def _has_credentials(self) -> bool:
        return bool(self._api_user and self._api_user.strip()
                     and self._api_secret and self._api_secret.strip())

    def _get_mime_type(self, file_path: str) -> str:
        """Determine MIME type from file extension."""
        ext = os.path.splitext(file_path)[1].lower()
        mime_map = {
            ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
            ".png": "image/png", ".webp": "image/webp",
            ".avif": "image/avif",
        }
        return mime_map.get(ext, "image/jpeg")

    def _build_image_factors(self, type_data: dict) -> list:
        """Convert Sightengine response scores into explainability factors."""
        factors = []

        ai_score = type_data.get("ai_generated", 0.0)
        factors.append({
            "name": "AI-Generated Content Score",
            "description": (
                "Sightengine neural classifier score indicating probability "
                "the entire image was synthetically generated by AI models "
                "(Midjourney, DALL-E, Stable Diffusion, Flux, Firefly, etc.)"
            ),
            "impact": "high",
            "score": round(float(ai_score), 4),
        })

        deepfake_score = type_data.get("deepfake", 0.0)
        factors.append({
            "name": "Deepfake Face-Swap Score",
            "description": (
                "Sightengine face manipulation detector score indicating "
                "probability that faces in the image have been swapped, "
                "replaced, or AI-manipulated to impersonate another person"
            ),
            "impact": "high",
            "score": round(float(deepfake_score), 4),
        })

        return factors

    def _classify_label(self, ai_score: float, deepfake_score: float) -> str:
        """Determine label from combined scores."""
        max_score = max(ai_score, deepfake_score)
        if max_score >= 0.75:
            return "manipulated"
        elif max_score >= 0.45:
            return "suspicious"
        else:
            return "authentic"

    async def _detect_image(
        self, file_path: str, options: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Detect AI-generated content and deepfakes in images."""
        job_id = f"sightengine-img-{uuid.uuid4().hex[:12]}"

        data = {
            "models": "genai,deepfake",
            "api_user": self._api_user,
            "api_secret": self._api_secret,
        }

        mime_type = self._get_mime_type(file_path)

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                with open(file_path, "rb") as f:
                    files = {"media": (os.path.basename(file_path), f, mime_type)}
                    response = await client.post(
                        SIGHTENGINE_IMAGE_URL, data=data, files=files
                    )

            res_data = response.json()

            if response.status_code != 200 or res_data.get("status") != "success":
                error_msg = res_data.get("error", {}).get("message", response.text[:300])
                return {
                    "provider": "sightengine",
                    "is_demo": False,
                    "job_id": job_id,
                    "status": "failed",
                    "error_message": f"Sightengine API error: {error_msg}",
                }

            type_data = res_data.get("type", {})
            ai_score = float(type_data.get("ai_generated", 0.0))
            deepfake_score = float(type_data.get("deepfake", 0.0))
            confidence = round(max(ai_score, deepfake_score), 4)
            label = self._classify_label(ai_score, deepfake_score)
            factors = self._build_image_factors(type_data)

            summary = (
                f"Sightengine AI Analysis: Image assessed as {label.upper()} — "
                f"AI-Generated probability {round(ai_score * 100, 1)}%, "
                f"Deepfake face-swap probability {round(deepfake_score * 100, 1)}%."
            )

            return {
                "provider": "sightengine",
                "is_demo": False,
                "job_id": job_id,
                "status": "completed",
                "media_type": "image",
                "label": label,
                "confidence": confidence,
                "raw_score": confidence,
                "result": {
                    "label": label,
                    "confidence": confidence,
                    "ai_generated": ai_score,
                    "deepfake": deepfake_score,
                    "provider_label": label.upper(),
                    "normalized_label": label,
                    "sightengine_raw": res_data,
                },
                "explanation": {
                    "summary": summary,
                    "factors": factors,
                },
                "modality_results": [
                    {
                        "modality": "image",
                        "label": label,
                        "confidence": confidence,
                    }
                ],
            }

        except Exception as e:
            return {
                "provider": "sightengine",
                "is_demo": False,
                "job_id": job_id,
                "status": "failed",
                "error_message": f"Sightengine API connection error: {str(e)}",
            }

    async def detect(
        self,
        file_path: str,
        media_type: str,
        options: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Submit image for deepfake / AI-generated content detection via Sightengine.
        Only supports image modality — video is handled by Reality Defender.
        """
        if not self.supports_modality(media_type):
            return {
                "provider": "sightengine",
                "status": "unsupported",
                "error_message": (
                    f"Sightengine provider supports 'image' only "
                    f"(received '{media_type}'). Use Reality Defender for video."
                ),
            }

        if not self._has_credentials():
            return {
                "provider": "sightengine",
                "status": "failed",
                "error_message": (
                    "Sightengine API credentials not configured. "
                    "Set SIGHTENGINE_API_USER and SIGHTENGINE_API_SECRET in .env"
                ),
            }

        return await self._detect_image(file_path, options)

    async def get_result(self, job_id: str) -> Dict[str, Any]:
        return {
            "provider": "sightengine",
            "is_demo": False,
            "job_id": job_id,
            "status": "completed",
        }
